### PR TITLE
Refresh of EVK-ANNA-B4 Zephyr board definition

### PR DESCRIPTION
**Pull request by perssonmagnus**
Minor changes and updates to EVK-ANNA-B4 board definition. Tested with nRF Connect 2.5 using blinky and button examples.

### CODE REVIEW

**Comment by ghost** [comment]
There might be a line to add for the buttons:
```
	buttons {
		compatible = "gpio-keys";
		button0: button_0 {
			gpios = <&gpio0 11 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;
			label = "Push button switch 0";
			zephyr,code = <INPUT_KEY_0>; // this line is new from Nordic DKs
		};
		button1: button_1 {
			gpios = <&gpio0 12 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;
			label = "Push button switch 1";
			zephyr,code = <INPUT_KEY_1>; // this line is new from Nordic DKs
```

**Comment by ghost** [comment]
These are also new in the nRF52833DK DTS file:
```
&uicr {
	gpio-as-nreset;
};
```
Should the USB port be enabled?
```
zephyr_udc0: &usbd {
	compatible = "nordic,nrf-usbd";
	status = "okay";
};
```
Should IEEE 802.15.4 be disabled?

**Comment by perssonmagnus** [comment]
Thanks for the review. I tested and added back 802.15.4 and USB, and fixed the other comments.

**Comment by ghost** [comment]
Looks good! Thanks for the updates.

**Review by ghost — APPROVED** [review]
Looks good. Completing the review here.

**Pull request merged**
